### ISSUE TITLE
Manjka postavka "enota" na računu pri uvozu iz Woocommerce

### ISSUE THREAD

**Issue by rainpikasi** [InvoiceFox/CebelcaBIZ-WooCommerce#11]
Zdravo,

Ko se kreira račun iz Woocommerce, pri postavki manjka enota in je treba vsako postavko posebej ročno popravljati. Trenutno je naročil malo, ker sem ravno začel s prodajo in to ni tak problem, zna pa postati v prihodnosti... Zalogo vodim samo v Woocommerce (zaradi narave artiklov ni smiselno, da jo vodim še v čebelci, saj bi si samo podvajal delo)

Je mogoče že kdo našel kako enostavnejšo rešitev? Recimo da bi dodal v kodo dodatno vrstico z default enoto, recimo "kos", ki jo potem "vrže" v polje ENOTA pri vsaki postavki na računu?

**Comment by refaktor** [comment]
Zdravo,

sam woocommerce kot sem uspel videti nima polja za enoto po defaultu. Če tako ali drugače dodate to polje (plugin ali custom koda) potem sem sedaj naredil da pri produktu pogleda _meta "unit_of_measurement". Če je to vneseno potem uproabi to kot enoto. 

Če želite dodati na vse artikle npr. "kos" potem bi to lahko storili v kodi na vrstici 374 v cebelcabiz.php. Lahko bi dodali to kot nastavitev. Bom dodal na todo.

**Comment by rainpikasi** [comment]
Zdravo,

sem poskusil dodati takole, da sem dodal na dveh mestih 

`						'unit_of_measurement'          => 'kos',`

še prikaz, kako sem dodal v kodi

```
`					$r2 = $api->createInvoice( array(
						'title'           => $invid,
						'date_sent'       => $date1,
						'date_to_pay'     => $date1,
						'date_served'     => $date1, // MAY NOT BE NULL IN SOME VERSIONS OF USER DBS
						'unit_of_measurement'          => 'kos',
						'id_partner'      => $clientId,
						'taxnum'          => '-',
						'doctype'         => $this->conf['document_to_make'] == 'advance_draft' ? 1 : 0,
						'id_document_ext' => $order->get_id(),
						'pub_notes'       => $this->conf['order_num_label'] . ' #' . $order->get_order_number()
					), $body2 );

					if ( $r2->isOk() ) {
						$invA = $r2->getData();
						$order->add_order_note( "Invoice No. {$invA[0]['title']} was created at {$this->conf['app_name']}." );
					}

				} elseif ( $this->conf['document_to_make'] == 'invoice_complete' ) {
					$r2 = $api->createInvoice( array(
						'title'           => $invid,
						'date_sent'       => $date1,
						'date_to_pay'     => $date1,
						'date_served'     => $date1, // MAY NOT BE NULL IN SOME VERSIONS OF USER DBS
						'unit_of_measurement'          => 'kos',
						'id_partner'      => $clientId,
						'taxnum'          => '-',
						'doctype'         => 0,
						'id_document_ext' => $order->get_id(),
						'pub_notes'       => $this->conf['order_num_label'] . ' #' . $order->get_order_number()
					), $body2 );`
```

Ampak enostavno ne dela.

**Comment by refaktor** [comment]
Merska enota se sedaj doda it woocommerca. Če pa jo želite ročno vpisati pa jo vpišete v tej vrstici. Parameter je "mu" (measuring unit). Vrstica: https://github.com/InvoiceFox/CebelcaBIZ-WooCommerce/blob/master/cebelcabiz.php#L389
