### ISSUE TITLE
PHP 8.x support

### ISSUE THREAD

**Issue by devdems** [InvoiceFox/CebelcaBIZ-WooCommerce#12]
Looks like the addon is not working on the new PHP 8 vestion.

**Comment by InvoiceFox** [comment]
Thanks for notifying us. I will test it. What version of Wordpress/Woocommerce were you using?

**Comment by refaktor** [comment]
I am working on a new version of plugin, my PHP is PHP Version 8.0.26, WC 7.1.1, WP 6.1.1 and I don't see any problems. What exactly doesn't work? What does the error log say?

**Comment by refaktor** [comment]
I created another bigger update, since I am doing all this on PHP 8.0.26 I will consider this issue closed for now. If you have any more information please reopen the issue.
