### ISSUE TITLE
Umik sporočila WC_Invoicefox:  ===== BEGIN ==== iz stderr

### ISSUE THREAD

**Issue by gresakg** [InvoiceFox/CebelcaBIZ-WooCommerce#14]
Berz potrebe polni error loge. Morda bi bilo smiselno uvesti dev mode oz. debug mode, pri katerem bi se to izpisalo, če je potrebno.

**Comment by refaktor** [comment]
Sem dodal konstanto WOOCOMM_INVFOX_DEBUG true/false, ki vklopi ali izklopi debug sporočila.
