### ISSUE TITLE
Polomljen predračun (0kb), ki se ga ne da odpreti, se pošilja ob nepričakovanih trenutkih

### ISSUE THREAD

**Issue by MorgusLethe** [InvoiceFox/CebelcaBIZ-WooCommerce#15]
Imam woocommerce trgovino s tremi plačilnimi metodami. Ena izmed njih je po predračunu - to je uradna opcija "wire transfer", vgrajena v woocommerce. V nastavitvah čebelca plugina imam izbrano avtomatsko akcijo, da kupec dobi predračun, ko naročilo vstopi v status "zadržano", kar se zgodi, če plača po predračunu, in vse deluje popolno.

Žal pa stranka dobi polomljen predračun z velikostjo 0 ali 1kb, ki se ga ne da odpreti, **tudi v primeru, če plača s kartico, čeprav naročilo nikoli ne vstopi v status zadržano.** Na čebelci ti polomljeni predračuni niso vidni, tako da ne vem točno, kaj jih generira in. Prisotni so tudi neki kitajski znaki, če poskusiš pdf odpreti na telefonu.

Prilagam sliko, kako izgleda polomljen predračun.

![predracun-broken](https://github.com/InvoiceFox/CebelcaBIZ-WooCommerce/assets/11448657/3c61fa72-6953-46c1-8ed1-78063f669185)

In še na telefonu:
![Screenshot 2023-12-15 142515](https://github.com/InvoiceFox/CebelcaBIZ-WooCommerce/assets/11448657/32069ada-86c7-4d81-b0a6-72ebdee91817)

**Comment by refaktor** [comment]
Hm ... drugače je s temi emaili tako, da jih pošlje sam woocommerce in pošiljanje sproži woocommerce. Ko se to sproži woocommerce pokliče naš plugin ki prenese PDF in ga doda kot priponko. Sam email in vsebina emaila pa je v domeni woocommerca in nastavitev.

Razlog da PDF ne dela, je najbrž v tem, da se v tem primeru predračun ni kreiral, tako da skuša poslati prazen predračun. 

Zakaj se to proži ob nepričakovanih trenutkih pa bi bilo treba ugotoviti. Najprej bi bilo dobro ugotoviti kdaj točno se proži, ker najbrž vseeno je neka interna logika pri tem. Npr na sliki emaila se vidi "Hvala za vaše naročilo!" Mogoče preverite kjer ste nastavili to vsebino emaila, če so kakšne nastavitve kdaj naj se pošlje ta email. 

Če mi posredujete več informacij o tem kdaj se pošlje, mogoče vedno od naročilu, tudi če ni npr. wire-transfer, potem bom lažje iskal naprej in našel težavo.

**Comment by MorgusLethe** [comment]
Težava ni, da woocommerce emaile proži nepričakovano. Se opravičujem za mojo slabo izbiro besed.

Bolje bi se izrazil z besedami "**čebelca plugin dodaja polomljen predračun zraven emailov, kamor predračun ne sodi**.

Dodatne informacije. **Želeno stanje:**
1. Imam 3 plačilne metode, predračun se uporablja in pošilja samo pri eni.
2. Za vsako naročilo kupec prejme 2 emaila, ne glede na plačilno metodo:
3.1 Prvi email: če metoda **ni** predračun dobi stranka "Hvala za naročilo. (brez priponk)" Ta prvi email je generiral woocommerce, ker je naročilo prešlo iz statusa "pending" v "Processing".
3.2 Če metoda **je** predračun dobi stranka "Hvala za naročilo, predračun morate še poravnati, najdete ga v priponki". Ta prvi email je generiral woocommerce, ker je naročilo prešlo iz statusa "pending" v "On Hold".
4. Drugi email: ne glede na plačilno metodo stranka dobi "Vaš paket je na poti, v priponki je račun".

**Dejansko stanje:**
3.1 Če metoda **ni** predračun stranka dobi "Hvala za naročilo. (in v priponki polomljen predračun)". Če metoda **je** predračun, vse deluje popolno.

**Z drugimi besedami čebelca plugin dodaja polomljen predračun, ko naročilo pride v status processing, čeprav je v nastavitvah plugina označeno, da naj v stanju processing čebelca ne naredi nobene akcije.** To je glavni vir problema, kakor ga razumem.

Sem ravnokar stestiral še eno pot. Opravil sem naročilo z metodo predračun. Prejel sem pravilen email s priponko. Nato sem naročilo spremenil iz "On hold" v "Processing", kar je neregularno za moj način dela. Woocommerce je poslal nov mail (pričakovano), čebelca pa je zraven dala PRAVILEN predračun, ki se je generiral, ko je naročilo bilo v stanju zadržano. Torej zopet je čebelca dodajala zraven priponko, čeprav je v nastavitvah plugina označeno "Brez akcije", ko pride naročilo v stanje processing.

**Comment by InvoiceFox** [comment]
Pozdravljeni,

hvala za tako dobro razlago. Se opravičujem da je malo trajalo a sem našel napako in jo popravil. Samo updejtajte zip plugina z zanjo kodo iz github-a in bi moralo delat. Lokalno sem testiral in deluje. Če bo še kaj narobe me lahko pokličete na 041 741 612, da to čimprej razrešimo.

LP
Janko

**Comment by MorgusLethe** [comment]
Sem preizkusil novo verzijo in deluje. Hvala!
