### ISSUE TITLE
Debug način je privzeto vklopljen

### ISSUE THREAD

**Issue by ilion227** [InvoiceFox/CebelcaBIZ-WooCommerce#16]
Pozdravljeni,

pri klicu konstruktorja InvfoxAPI je zadnji parameter vedno nastavljen na `true`. (primer enega klica je spodaj, teh klicev je več v kodi)

https://github.com/InvoiceFox/CebelcaBIZ-WooCommerce/blob/caf22b63d88f473f14a3ce4aa40b3dcd158aae87/cebelcabiz.php#L210

Ta parameter predstavlja debugMode. 
https://github.com/InvoiceFox/CebelcaBIZ-WooCommerce/blob/caf22b63d88f473f14a3ce4aa40b3dcd158aae87/lib/invfoxapi.php#L38-L40

Je možno to spremeniti, da bo privzeto `false` in se to vrednost shrani kot spremenljivko, tako da se nastavlja na 1 mestu v kodi?

---

Ta debug način _lahko_ povzroči težave na public delu WooCommerce (checkout), saj je možno, da se hook, ki vsebuje to kodo, sproži ob checkoutu.

Zaradi debuga in posledično izpisa podatkov (echo), se v response vrine še dodaten tekst, kar povzroči, da request na frontend ni uspešen (pričakuje se JSON response, vrnjen pa je debug tekst + JSON response).

**Comment by InvoiceFox** [comment]
Šele sedaj sem videl to. Pa ravno to je povzročalo debug output pri nekaterih, ki mu nisem uspel najti razloga, če pa bi videl vaš issue pa bi to bilo rešeno že junija. Tako da hvala, in se opravičujem.
