### ISSUE TITLE
Additional fees are not imported into Cebelca.biz

### ISSUE THREAD

**Issue by timihras** [InvoiceFox/CebelcaBIZ-WooCommerce#9]
Additional fees that are added before the order confirmation or manually after the order is placed are skipped when creating the invoice in Cebelca.

1. Go to Woocommerce -> Orders
2. Create a new order or open an existing one
3. Click Add items -> Add fee 
4. Enter fee amount and save the order
5. Click "Cebelca.biz: Make Invoice"

Expected: Fees are a part of the created invoice
Actual: Fees are not imported in the created invoice

**Comment by refaktor** [comment]
thank you. I will teste the case and try to add this.

**Comment by rokelvisar** [comment]
Confirming issue - same here.

**Comment by InvoiceFox** [comment]
This was solved in one of latest updates. I will close the issue, thank you.
